/**
 * Checks on the built site. There is no server, so these read the files
 * straight off disk.
 *
 * public/index.html is hand-maintained; catalogue.html and products/*.html
 * are generated by tools/build-site.mjs. Several tests below exist to catch
 * the two drifting apart.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { readFile, access, readdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC = join(ROOT, "public");

const catalog = JSON.parse(await readFile(join(ROOT, "catalog.json"), "utf8"));
const read = (rel) => readFile(join(PUBLIC, rel), "utf8");

const home = await read("index.html");
const directory = await read("catalogue.html");
const productFiles = (await readdir(join(PUBLIC, "products"))).filter((f) => f.endsWith(".html"));
const products = Object.fromEntries(
  await Promise.all(productFiles.map(async (f) => [f, await read(join("products", f))]))
);

const everyPage = [
  ["index.html", home],
  ["catalogue.html", directory],
  ...Object.entries(products).map(([f, html]) => [`products/${f}`, html])
];

/* ---------------------------------------------------------------- *
 * Structure
 * ---------------------------------------------------------------- */

test("there is one product page per catalogue item, and no orphans", async () => {
  const expected = catalog.items.map((i) => `${i.code}.html`).sort();
  assert.deepEqual(productFiles.sort(), expected);
});

test("every page carries the gate, the nav and the footer", async () => {
  for (const [name, html] of everyPage) {
    assert.match(html, /<div class="gate" id="gate"/, `${name}: no gate`);
    assert.match(html, /id="gate-enter"[^>]*disabled/, `${name}: gate button not disabled in markup`);
    assert.match(html, /<header class="site-header" inert>/, `${name}: header not inert`);
    assert.match(html, /<footer class="site-footer" inert>/, `${name}: footer not inert`);
    assert.match(html, /href="[^"]*catalogue\.html"/, `${name}: no link to the catalogue`);
  }
});

test("gate.js is render-blocking in the head of every page", async () => {
  for (const [name, html] of everyPage) {
    const head = html.slice(0, html.indexOf("<body"));
    assert.match(head, /<script src="[^"]*gate\.js"><\/script>/, `${name}: gate.js not in head`);
    assert.equal(/<script[^>]*gate\.js[^>]*(defer|async)/.test(head), false,
      `${name}: gate.js must not be deferred — it reintroduces the flash`);
  }
});

test("no page carries inline style or script", async () => {
  for (const [name, html] of everyPage) {
    assert.equal(/\sstyle=["']/.test(html), false, `${name}: inline style attribute`);
    assert.equal(/<script(?![^>]*\ssrc=)/i.test(html), false, `${name}: inline <script>`);
  }
});

/* ---------------------------------------------------------------- *
 * Links
 * ---------------------------------------------------------------- */

test("every local file each page references exists", async () => {
  for (const [name, html] of everyPage) {
    const base = join(PUBLIC, dirname(name));
    const refs = [...html.matchAll(/(?:href|src)="((?:\.\.?\/)?[^":#?][^":#]*\.(?:css|js|html))"/g)].map((m) => m[1]);
    assert.ok(refs.length >= 3, `${name}: expected stylesheet, scripts and links`);
    for (const ref of refs) {
      await assert.doesNotReject(access(resolve(base, ref)), `${name}: missing ${ref}`);
    }
  }
});

test("in-page anchors resolve on the page that uses them", async () => {
  for (const [name, html] of everyPage) {
    const ids = new Set([...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));
    const anchors = [...html.matchAll(/href="#([^"]+)"/g)].map((m) => m[1]);
    for (const anchor of anchors) {
      assert.ok(ids.has(anchor), `${name}: href="#${anchor}" has no matching id`);
    }
  }
});

test("the directory links to every product page", async () => {
  for (const item of catalog.items) {
    assert.match(directory, new RegExp(`href="products/${item.code}\\.html"`),
      `catalogue.html does not link to ${item.code}`);
  }
});

/* ---------------------------------------------------------------- *
 * Generated content matches catalog.json
 * ---------------------------------------------------------------- */

test("the generated pages match catalog.json exactly", async () => {
  const { directoryPage, productPage } = await import("../tools/build-site.mjs");
  assert.equal(directory, directoryPage(catalog), "run `npm run build`");
  for (const item of catalog.items) {
    assert.equal(products[`${item.code}.html`], productPage(item, catalog),
      `${item.code}.html is stale — run \`npm run build\``);
  }
});

test("each product page states its price, format and stock", async () => {
  for (const item of catalog.items) {
    const html = products[`${item.code}.html`];
    assert.match(html, new RegExp(`\\$${item.price.toLocaleString("en-US")}`), `${item.code}: price missing`);
    assert.match(html, new RegExp(`\\$${(item.price / item.vials).toFixed(2)}`), `${item.code}: per-vial price missing`);
    assert.ok(html.includes(item.format.replace(/&/g, "&amp;")), `${item.code}: format missing`);
    assert.match(html, /Warehouse stock/, `${item.code}: stock block missing`);
  }
});

test("catalogue data stays internally consistent", async () => {
  for (const item of catalog.items) {
    assert.ok(item.price > 0, `${item.code} has no price`);
    assert.ok(item.format, `${item.code} has no format`);
    assert.equal(item.stock.length, catalog.warehouses.length, `${item.code} stock/warehouse mismatch`);
    assert.ok(["sequence", "blend", "ancillary"].includes(item.category), `${item.code} bad category`);
  }
  const codes = catalog.items.map((i) => i.code);
  assert.equal(new Set(codes).size, codes.length, "duplicate product codes");
});

/* ---------------------------------------------------------------- *
 * The framing the whole site rests on
 * ---------------------------------------------------------------- */

test("the research-use framing is on every page", async () => {
  for (const [name, html] of everyPage) {
    assert.match(html, /Research use only/i, `${name}: missing the chip`);
    assert.match(html, /not for human or veterinary use/i, `${name}: missing the disclaimer`);
  }
});

test("no page makes a therapeutic or dosing claim", async () => {
  const forbidden = [
    /\bdos(e|ing|age)\b/i, /\btreats?\b/i, /\bcures?\b/i, /\btherapy\b/i,
    /\bweight loss\b/i, /\bfat loss\b/i, /\banti-aging\b/i, /\bprescri/i,
    /\bpatient/i
  ];
  for (const [name, html] of everyPage) {
    // Disclaimers necessarily name what the products are NOT — "publishes no
    // dosing guidance", "not for diagnostic or therapeutic use". Those are the
    // opposite of a claim, so exclude them and test everything else.
    const body = html
      .replace(/<section class="section" id="compliance">[\s\S]*?<\/section>/, "")
      .replace(/<p class="product-ruo">[\s\S]*?<\/p>/g, "")
      .replace(/<div class="gate"[\s\S]*?<\/div>\s*<\/div>/, "");
    assert.equal(/id="compliance"|class="product-ruo"|class="gate"/.test(body), false,
      `${name}: a disclaimer block was not excluded — the exclusions have drifted`);
    for (const pattern of forbidden) {
      assert.equal(pattern.test(body), false, `${name} matches ${pattern}`);
    }
  }
});

/* ---------------------------------------------------------------- *
 * Home page specifics
 * ---------------------------------------------------------------- */

test("the home page's featured products all exist", async () => {
  const featured = [...home.matchAll(/href="products\/([^"]+)\.html"/g)].map((m) => m[1]);
  assert.ok(featured.length >= 4, "expected a few featured products");
  const codes = new Set(catalog.items.map((i) => i.code));
  for (const code of featured) assert.ok(codes.has(code), `featured ${code} is not in the catalogue`);
});

test("the chromatogram's integration table agrees with the purity figure", async () => {
  const areas = [...home.matchAll(/<td>(\d+\.\d\d)<\/td>\s*<\/tr>/g)].map((m) => Number(m[1]));
  assert.equal(areas.length, 4, "expected four integrated peaks");
  const total = areas.reduce((sum, v) => sum + v, 0);
  assert.ok(Math.abs(total - 100) < 0.01, `area percentages sum to ${total}, not 100`);
  const headline = Number(home.match(/<span class="v hero-figure">([\d.]+) %/)[1]);
  assert.equal(Math.max(...areas), headline, "main peak differs from the stated purity");
});

test("every copy button names an element holding an address", async () => {
  for (const [name, html] of everyPage) {
    const targets = [...html.matchAll(/data-copy="([^"]+)"/g)].map((m) => m[1]);
    assert.ok(targets.length >= 1, `${name}: no copy button`);
    for (const id of targets) {
      const block = html.match(new RegExp(`id="${id}"[^>]*>([^<]+)<`));
      assert.ok(block, `${name}: no element with id="${id}"`);
      assert.match(block[1].trim(), /^[^\s@]+@[^\s@]+\.[^\s@]+$/, `${name}: id="${id}" is not an address`);
    }
  }
});

/* ---------------------------------------------------------------- *
 * The brand lives in exactly one place
 * ---------------------------------------------------------------- */

test("no page carries a name or address brand.json did not produce", async () => {
  // The previous name was baked into every page, which is part of why an
  // uncleared one got as far as it did. This keeps brand.json authoritative.
  const { brand } = await import("../tools/build-site.mjs");
  const allowed = [brand.name, brand.emails.general, brand.emails.coa, brand.domain];

  for (const [name, html] of everyPage) {
    const addresses = [...html.matchAll(/[\w.+-]+@[\w.-]+\.\w+/g)].map((m) => m[0]);
    for (const address of addresses) {
      assert.ok(allowed.includes(address), `${name}: ${address} is not in brand.json`);
    }
    assert.equal(/\bpeptra\b/i.test(html), false, `${name}: the old brand name survives`);
  }
});

test("the home page is generated from its template and brand.json", async () => {
  const { brand, render } = await import("../tools/build-site.mjs");
  const template = await readFile(join(ROOT, "src", "home.html"), "utf8");
  assert.equal(home, render(template, brand), "run `npm run build`");
});

test("a placeholder domain never writes a CNAME", async () => {
  // A CNAME naming a domain that does not resolve takes the live site down.
  const { brand } = await import("../tools/build-site.mjs");
  const placeholder = /\.(example|invalid|test|localhost)$/.test(brand.domain);

  if (placeholder) {
    await assert.rejects(access(join(PUBLIC, "CNAME")),
      `brand.domain is a placeholder (${brand.domain}) but a CNAME was written`);
  } else {
    assert.equal((await read("CNAME")).trim(), brand.domain);
  }
});
